stock_trans:
  outputs:
    dev:
      dbname: stock
      host: localhost
      pass: admin123
      port: 5432
      schema: public
      threads: 1
      type: postgres
      user: admin
  target: dev
